### ISSUE TITLE
Write up project proposal

### ISSUE THREAD

**Issue by guidozuc** [HarshitaJain0905/SMS_Spam_701#1]
Use the template given by the unit coordinators. Refer to CRA.

**Comment by HarshitaJain0905** [comment]
Completed the remaining sections. Left wit referencing and formatting.

**Comment by HarshitaJain0905** [comment]
[Document8.docx](https://github.com/HarshitaJain0905/SMS_Spam_701/files/1235738/Document8.docx)

**Comment by HarshitaJain0905** [comment]
Proposal doc completed.

**Comment by HarshitaJain0905** [comment]
[Document8.pdf](https://github.com/HarshitaJain0905/SMS_Spam_701/files/1236746/Document8.pdf)
